import { Home } from "lucide-react";
import Sidebar from "./component/Sidebar";
import "./globals.css";



export const metadata = {
  title: "Spotify clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body > 
        {children}
      </body>
    </html>
  );
}
