
import Sidebar from "./component/Sidebar";
import "./globals.css";



export const metadata = {
  title: "Spotify clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex gap-4 box-border p-2 bg-black text-white "> 
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
